name: Deploy Astro site

on:
  push:
    branches:
      - main  # Cambia si usas otra rama para producción
  workflow_dispatch: # Permite ejecutar el workflow manualmente

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci # Usa `npm ci` en lugar de `npm install` para builds más confiables

      - name: Build site
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist  # Asegura que "dist" es el directorio correcto

  publish:
    needs: deploy  # Espera a que el job "deploy" termine
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

